"""Initial PostgreSQL schema

Revision: 0003
"""

import sqlalchemy as sa

from alembic import op

revision = "0003"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("telegram_id > 0", name="ck_user_telegram_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blocker_id", sa.Integer(), nullable=False),
        sa.Column("blocked_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("blocker_id != blocked_id", name="ck_block_self"),
        sa.ForeignKeyConstraint(
            ["blocked_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="uq_block_pair"),
    )
    op.create_index(op.f("ix_blocks_blocked_id"), "blocks", ["blocked_id"], unique=False)
    op.create_index(op.f("ix_blocks_blocker_id"), "blocks", ["blocker_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_low_id", sa.Integer(), nullable=False),
        sa.Column("user_high_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("user_low_id < user_high_id", name="ck_match_order"),
        sa.ForeignKeyConstraint(
            ["user_high_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_low_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_low_id", "user_high_id", name="uq_match_pair"),
    )
    op.create_index(op.f("ix_matches_user_high_id"), "matches", ["user_high_id"], unique=False)
    op.create_index(op.f("ix_matches_user_low_id"), "matches", ["user_low_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=6), nullable=False),
        sa.Column("seeking", sa.String(length=6), nullable=False),
        sa.Column("city", sa.String(length=60), nullable=False),
        sa.Column("city_normalized", sa.String(length=120), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("bio", sa.String(length=300), nullable=False),
        sa.Column("photo_file_id", sa.String(length=512), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("own_city_only", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("gender IN ('male', 'female')", name="ck_profile_gender"),
        sa.CheckConstraint("seeking IN ('male', 'female', 'any')", name="ck_profile_seeking"),
        sa.CheckConstraint(
            "18 <= min_age AND min_age <= max_age AND max_age <= 99", name="ck_profile_range"
        ),
        sa.CheckConstraint("age BETWEEN 18 AND 99", name="ck_profile_age"),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_profile_latitude"
        ),
        sa.CheckConstraint("length(bio) <= 300", name="ck_profile_bio"),
        sa.CheckConstraint("length(city) BETWEEN 2 AND 60", name="ck_profile_city"),
        sa.CheckConstraint("length(name) BETWEEN 2 AND 40", name="ck_profile_name"),
        sa.CheckConstraint("length(photo_file_id) > 0", name="ck_profile_photo"),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_profile_longitude"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_profiles_city_normalized"), "profiles", ["city_normalized"], unique=False
    )
    op.create_index(op.f("ix_profiles_is_active"), "profiles", ["is_active"], unique=False)
    op.create_index("ix_profiles_location", "profiles", ["latitude", "longitude"], unique=False)
    op.create_table(
        "reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('like', 'pass')", name="ck_reaction_kind"),
        sa.CheckConstraint("from_user_id != to_user_id", name="ck_reaction_self"),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_user_id", "to_user_id", name="uq_reaction_pair"),
    )
    op.create_index(op.f("ix_reactions_from_user_id"), "reactions", ["from_user_id"], unique=False)
    op.create_index(op.f("ix_reactions_to_user_id"), "reactions", ["to_user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("reported_user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("status IN ('pending', 'reviewed')", name="ck_report_status"),
        sa.CheckConstraint("length(reason) BETWEEN 1 AND 320", name="ck_report_reason"),
        sa.CheckConstraint("reporter_id != reported_user_id", name="ck_report_self"),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reports_reported_user_id"), "reports", ["reported_user_id"], unique=False
    )
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_index(
        "uq_report_pending",
        "reports",
        ["reporter_id", "reported_user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_report_pending", table_name="reports", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_reported_user_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_reactions_to_user_id"), table_name="reactions")
    op.drop_index(op.f("ix_reactions_from_user_id"), table_name="reactions")
    op.drop_table("reactions")
    op.drop_index("ix_profiles_location", table_name="profiles")
    op.drop_index(op.f("ix_profiles_is_active"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_city_normalized"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_matches_user_low_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_user_high_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_blocks_blocker_id"), table_name="blocks")
    op.drop_index(op.f("ix_blocks_blocked_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_table("users")
    # ### end Alembic commands ###
